/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        AppBtn: (typeof import('./src/components/app/AppBtn.vue'))['default']
        AppHeader: (typeof import('./src/components/app/layout/AppHeader.vue'))['default']
        AppHero: (typeof import('./src/components/app/layout/AppHero.vue'))['default']
        AppKBD: (typeof import('./src/components/app/AppKBD.vue'))['default']
        AppSidebar: (typeof import('./src/components/app/layout/AppSidebar.vue'))['default']
        DarkModeToggle: (typeof import('./src/components/app/DarkModeToggle.vue'))['default']
        HalfMoon: (typeof import('./src/components/icons/HalfMoon.vue'))['default']
        RouterLink: (typeof import('vue-router'))['RouterLink']
        RouterView: (typeof import('vue-router'))['RouterView']
        SunLight: (typeof import('./src/components/icons/SunLight.vue'))['default']
        VueyeBody: (typeof import('./src/components/core/VueyeTable/VueyeBody/VueyeBody.vue'))['default']
        VueyeDropdown: (typeof import('./src/components/core/VueyeTable/util-components/VueyeDropdown.vue'))['default']
        VueyeHead: (typeof import('./src/components/core/VueyeTable/VueyeHead/VueyeHead.vue'))['default']
        VueyePagination: (typeof import('./src/components/core/VueyeTable/VueyePagination/VueyePagination.vue'))['default']
        VueyeTable: (typeof import('./src/components/core/VueyeTable/VueyeTable.vue'))['default']
    }
}
